In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3])
print('arr1 type : ', type(arr1))
print('arr1 array 형태 : ', arr1.shape)

arr2 = np.array([[1,2,3], 
                [4,5,6]])
print('arr2 type : ', type(arr2))
print('arr2 array 형태 : ', arr2.shape)

arr3 = np.array([[1,2,3]])
print('arr3 type : ', type(arr3))
print('arr3 array 형태 : ', arr3.shape)

arr1 type :  <class 'numpy.ndarray'>
arr1 array 형태 :  (3,)
arr2 type :  <class 'numpy.ndarray'>
arr2 array 형태 :  (2, 3)
arr3 type :  <class 'numpy.ndarray'>
arr3 array 형태 :  (1, 3)


In [4]:
print('arr1 : {:0}차원, arr2: {:1}차원, arr3: {:2}차원'.format(arr1.ndim, arr2.ndim, arr3.ndim))

arr1 : 1차원, arr2: 2차원, arr3:  2차원


In [5]:
list1 = [1,2,3]
print(type(list1))
arr1 = np.array(list1)
print(type(arr1))
print(arr1, arr1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
list2 = [1, 2, 'test'] # int32, string을 가진 list
arr2 = np.array(list2)
print(arr2, arr2.dtype)

list3 = [1, 2, 3.0] # int32, float을 가진 list
arr3 = np.array(list3)
print(arr3, arr3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [7]:
arr_int = np.array([1,2,3])
arr_float = arr_int.astype('float64')
print(arr_float, arr_float.dtype)

arr_int1 = arr_float.astype('int32')
print(arr_int1, arr_int1.dtype)

arr_float1 = np.array([1.1, 2.1, 3.1])
arr_int2 = arr_float1.astype('int32')
print(arr_int2, arr_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [8]:
sequence_arr = np.arange(10) # 0 to 9
print(sequence_arr)
print(sequence_arr.dtype, sequence_arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [9]:
zero_arr = np.zeros((3,2), dtype='int32') # 2차원 row 3개, col 2개
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

one_arr = np.ones((3, 2)) # 2차원 row 3개, col 2개
print(one_arr)
print(one_arr.dtype, one_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
arr1 = np.arange(10)
print('arr1 : \n', arr1)

arr2 = arr1.reshape(2, 5)
print('arr2 : \n', arr2)

arr3 = arr1.reshape(5, 2)
print('arr3 : \n', arr3)

arr1 : 
 [0 1 2 3 4 5 6 7 8 9]
arr2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
arr1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
arr1 = np.arange(10) # [0,1,2,3,4,5,6,7,8,9]
print(arr1)

arr2 = arr1.reshape(-1, 5) # row -1, col 5 -> col을 5로 row는 알아서
print('arr2 shape : ', arr2.shape) # (2, 5)

arr3 = arr1.reshape(5, -1) # row 5, col -1 -> row를 5로 col을 알아서
print('arr3 shape : ', arr3.shape) # (5, 2)

[0 1 2 3 4 5 6 7 8 9]
arr2 shape :  (2, 5)
arr3 shape :  (5, 2)


In [ ]:
arr1 = np.arange(8)
arr3d = arr1.reshape((2, 2, 2))
print("arr3d : \n", arr3d.tolist()) # ndarray to list

# 3차원 ndarray를 2차원 ndarray로 변환
arr5 = arr3d.reshape(-1, 1) # 2차원으로 변경
print('arr5 : \n', arr5.tolist())
print('arr5 shape :', arr5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
arr6 = arr1.reshape(-1, 1)
print('arr6 : \n', arr6.tolist())
print('arr6 shape : ', arr6.shape)


arr3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
arr5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr5 shape : (8, 1)
arr6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
arr6 shape :  (8, 1)


In [ ]:
# 1 to 9 1d ndarray create
arr1 = np.arange(start=1, stop= 10)
print('arr : ', arr1)

# index is starting from 0
value = arr1[2]
print('value : ', value)
print(type(value))

arr :  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [ ]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3, 3)
print(arr2d)

print('(row = 0, col = 0) index 가리키는 값 : ', arr2d[0,0])
print('(row = 0, col = 1) index 가리키는 값 : ', arr2d[0,1])
print('(row = 1, col = 0) index 가리키는 값 : ', arr2d[1,0])
print('(row = 2, col = 2) index 가리키는 값 : ', arr2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col = 0) index 가리키는 값 :  1
(row = 0, col = 1) index 가리키는 값 :  2
(row = 1, col = 0) index 가리키는 값 :  4
(row = 2, col = 2) index 가리키는 값 :  9


In [ ]:
arr1 = np.arange(start=1, stop=10)
arr3 = arr1[0:3]
print("arr1 dtype : ", arr1.dtype)
print("type(arr1) : ", type(arr1))
print('arr3 : ', arr3)
print('type(arr3) : ', type(arr3))

arr1 dtype :  int32
type(arr1) :  <class 'numpy.ndarray'>
arr3 :  [1 2 3]
type(arr3) :  <class 'numpy.ndarray'>


In [ ]:
arr1 = np.arange(start=1, stop=10) # [1 2 3 4 5 6 7 8 9]
arr4 = arr1[:3]
print(arr4)

arr5 = arr1[3:]
print(arr5)

arr6 = arr1[:]
print(arr6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
arr1d = np.arange(start=1, stop= 10)
arr2d = arr1d.reshape(3, 3)
print('arr2d : \n', arr2d)

print('arr2d[0:2, 0:2] \n', arr2d[0:2, 0:2])
print('arr2d[1:3, 0:3] \n', arr2d[1:3, 0:3])
print('arr2d[1:3, :] \n', arr2d[1:3, 0:3])
print('arr2d[:, :] \n', arr2d[1:3, 0:3])
print('arr2d[:2, 1:] \n', arr2d[1:3, 0:3])
print('arr2d[:2, 0] \n', arr2d[:2, 0])

arr2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
arr2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
arr2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
arr2d[:, :] 
 [[4 5 6]
 [7 8 9]]
arr2d[:2, 1:] 
 [[4 5 6]
 [7 8 9]]
arr2d[:2, 0] 
 [1 4]


In [ ]:
print(arr2d[0])
print(arr2d[1])
print('arr2d[0] shape: ', arr2d[0].shape, 'arr2d[1] shape : ', arr2d[1].shape)

[1 2 3]
[4 5 6]
arr2d[0] shape:  (3,) arr2d[1] shape :  (3,)


In [ ]:
arr1d = np.arange(start=1, stop=10)
arr2d = arr1d.reshape(3, 3)

arr3 = arr2d[[[0, 1]], 2]
print('arr2d[[0, 1], 2] => ', arr3.tolist())

arr4 = arr2d[[0, 1], 0:2]
print('arr2d[[0, 1], 0:2] => ', arr4.tolist())

arr5 = arr2d[[0, 1]]
print('arr2d[[0, 1]] => ', arr5.tolist())

arr2d[[0, 1], 2] =>  [[3, 6]]
arr2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
arr2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


In [ ]:
arr1d = np.arange(start=1, stop=10)
# [] 안에 arr1d > 5 Boolean indexing을 적용
arr3 = arr1d[arr1d > 5]
print('arr1d > 5 불린 인덱싱 결과 값 : ', arr3);

arr1d > 5 불린 인덱싱 결과 값 :  [6 7 8 9]


In [ ]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
arr3 = arr1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 : ', arr3)

불린 인덱스로 필터링 결과 :  [6 7 8 9]


In [ ]:
# 행렬 정렬 = sort()와 argsort()
org_arr = np.array([3, 1, 9, 5])
print('원본 행렬 : ', org_arr)

# np.sort() : 원 행렬은 유지되고 sort된 행렬을 return
sort_arr1 = np.sort(org_arr)
print('np.sort() 호출 후 반환된 정렬 행렬 : ', sort_arr1)
print('np.sort() 호출 후 원본 행렬 : ', org_arr)

# ndarray.sort() : 원 행렬은 sort되고 None을 return
sort_arr2 = org_arr.sort()
print('org_arr.sort() 호출 후 반환된 행렬 : ', sort_arr2)
print('org_arr.sort() 호출 후 원본 행렬 : ', org_arr)

원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_arr.sort() 호출 후 반환된 행렬 :  None
org_arr.sort() 호출 후 원본 행렬 :  [1 3 5 9]


In [ ]:
# 내림차순으로 정렬하고 싶을 때 [::-1]
sort_arr1_desc = np.sort(org_arr)[::-1]
print('내림차순으로 정렬 : ', sort_arr1_desc)

내림차순으로 정렬 :  [9 5 3 1]


In [12]:
arr2d = np.array([[8, 12], [7, 1]])

sort_arr2d_axis0 = np.sort(arr2d, axis=0) # row방향으로 sort
print('로우 방향으로 정렬:\n', sort_arr2d_axis0)

sort_arr2d_axis1 = np.sort(arr2d, axis=1) # col방향으로 sort
print('칼럼 방향으로 정렬:\n', sort_arr2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [13]:
org_arr = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_arr) # 정렬 행본의 원본 행렬 인덱스를 ndarray형으로 return
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]


In [14]:
org_arr = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_arr)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


In [15]:
import numpy as np

name_arr = np.array( ['John',  'Mike', 'Sarah', 'Kate', 'Samuel'])
score_arr = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_arr)
print('성적 오름차순 정렬시 score_arr의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_arr의 이름 출력 : ', name_arr[sort_indices_asc])

성적 오름차순 정렬시 score_arr의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_arr의 이름 출력 :  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [17]:
A = np.array([[1, 2, 3],
            [4, 5, 6]])
B = np.array([[7, 8],
            [9, 10],
            [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과: \n', dot_product)


행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


In [18]:
A = np.array([ [1, 2] ,
                [3, 4] ] )
transpose_mat = np.transpose(A)
print('A의 전치 행렬: \n', transpose_mat)

A의 전치 행렬: 
 [[1 3]
 [2 4]]
